ignore_patterns:
  - ".*^(redhat).*"
  - ".*snapshot.*"

targets:
  stage-ga:
  - bucket: "stage-maven-ga"
    prefix: ga
  stage-ea:
  - bucket: "stage-maven-ea"
    prefix: earlyaccess/all
  stage-maven: # collection of stage-ea and stage-ga
  - bucket: "stage-maven-ga"
    prefix: ga
  - bucket: "stage-maven-ea"
    prefix: earlyaccess/all
  stage-npm:
  - bucket: "stage-npm-npmjs"
    prefix: /
    registry: "npm.stage.registry.redhat.com"
