name: Linters

on:
  pull_request:

  push:
    branches:
      - master
      - release_*

jobs:
  flake8:
    name: Flake8 for Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [ "3.9", "3.10", "3.11", "3.12" ]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools tox

      - name: Run flake8 on python${{ matrix.python-version }}
        run: python -m tox -e flake8

  pylint:
    name: Pylint analyzer for Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [ "3.9", "3.10", "3.11", "3.12" ]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools tox

      - name: Run pylint on python${{ matrix.python-version }}
        run: python -m tox -e pylint

  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Run ShellCheck
        uses: containerbuildsystem/actions/shellcheck@master

  mypy:
    name: mypy type checker for Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [ "3.9" ]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools tox

      - name: Run mypy on python${{ matrix.python-version }}
        run: python -m tox -e mypy

  # bandit:
  #   name: Bandit analyzer for Python ${{ matrix.python-version }}
  #   runs-on: ubuntu-latest

  #   strategy:
  #     matrix:
  #       python-version: [ "3.8" ]

  #   steps:
  #     - uses: actions/checkout@v1
  #     - uses: actions/setup-python@v4
  #       with:
  #         python-version: ${{ matrix.python-version }}
  #     - name: Install dependencies
  #       run: |
  #         python -m pip install --upgrade pip setuptools tox

  #     - name: Run bandit analyzer on python${{ matrix.python-version }}
  #       run: python -m tox -e bandit
