####
# This Containerfile is used to build the container for charon
#
# charon requires python 3
#
# 0. Step into the project dir
#
# 1. Build the image
#   docker/podman build -t charon:1.0.0 -f image/Containerfile .
#
# 2. Run the container as daemon, mount the host ~/upload/ path to container /root/upload/ path,
#   the uploading path is the dir location where you will upload the tarballs from
#   add -e to set specific environment variables, such as: AWS_PROFILE, aws_endpoint_url, bucket
#   docker/podman run -dit -v ~/upload/:/home/charon/upload/ --name charon charon:1.0.0
#
# 3. Execute the container
#   docker/podman exec -it charon bash
#
# 4. Start using uploader
#   charon upload/delete from /home/charon/upload/...
###
FROM registry.access.redhat.com/ubi8-minimal:latest

LABEL description="Charon upload image" \
      summary="Charon upload image" \
      maintainer="RedHat SPMM Dev Team" \
      vendor="Red Hat, Inc." \
      distribution-scope="public" \
      vcs-type="git" 

ARG USER=charon
ARG UID=10000
ARG HOME_DIR=/home/${USER}
ARG GIT_BRANCH=main

WORKDIR ${HOME_DIR}

USER root

RUN microdnf install -y git-core python3.9 shadow-utils \
    && microdnf clean all
RUN pip3 install --no-cache-dir --upgrade pip
RUN useradd -d ${HOME_DIR} -u ${UID} -g 0 -m -s /bin/bash ${USER} \
    && chown ${USER}:0 ${HOME_DIR} \
    && chmod -R g+rwx ${HOME_DIR} \
    && chmod g+rw /etc/passwd

RUN git clone -b ${GIT_BRANCH} --depth 1 https://github.com/Commonjava/charon.git
RUN cp ./charon/image/2022-IT-Root-CA.pem /etc/pki/ca-trust/source/anchors/2022-IT-Root-CA.pem
RUN update-ca-trust extract

RUN pip3 install --no-cache-dir -r ./charon/requirements.txt
RUN pip3 wheel ./charon
RUN pip3 install --no-cache-dir ./*.whl
RUN rm -rf ./charon ./*.whl

RUN microdnf remove git-core shadow-utils && microdnf clean all

USER ${USER}

ENV HOME=${HOME_DIR} \
    LANG=en_US.UTF-8

CMD ["/usr/local/bin/charon"]
